
fun main() {
    WallService.add(Post(0,10,1,1,1,"НЕТ",true,true,true,
            0,
            0,
            "0",
            0,
            0,
            0,
            true,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        )
    )
    println(WallService.posts[0])
    WallService.add(
        Post(
            0,
            17,
            17,
            17,
            17,
            "DDD",
            true,
            true,
            true,
            0,
            0,
            "0",
            0,
            0,
            0,
            true,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        )
    )
    println(WallService.posts[1])
    WallService.add(
        Post(
            0,
            22,
            22,
            22,
            22,
            "DDD",
            true,
            true,
            true,
            0,
            0,
            "0",
            0,
            0,
            0,
            true,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        )
    )
    println(WallService.posts[2])
    WallService.add(
        Post(
            3,
            44,
            44,
            44,
            44,
            "DDD",
            true,
            true,
            true,
            0,
            0,
            "0",
            0,
            0,
            0,
            true,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        )
    )
    println(WallService.posts[3])
    println()
    WallService.update(
        Post(
            2,
            2,
            2,
            2,
            2,
            "ДА",
            false,
            false,
            false,
            0,
            0,
            "0",
            0,
            0,
            0,
            true,
            0,
            likes,
            commentInfo,
            copyrights,
            repost,
            postSources,
            geos,
            view,
            donuts
        )
    )
    println(WallService.posts[2])
    println(WallService.createComment(2, comment))
    println(WallService.createComment(3, comment))
    println(WallService.createComment(1, comment))
    println()
    println(WallService.reports(3,5))


}


